### PR TITLE
Add configs for ESLint.

### PR DESCRIPTION
**Pull request by saitheexplorer**
- Add base config for ESLint.
- Add additional config for ES6 support.

### CODE REVIEW

**Comment by saitheexplorer** [comment]
@nectarom/developers can we work on creating a couple of `.eslintrc` files? Would like to start the migration to ESLint and given that you guys have already been working in ES6, figured you have some presets.

**Comment by daniel-casper** [comment]
Absolutely yea! Let's discuss soon.

**Comment by saitheexplorer** [comment]
we can do this async- let's just discuss on this PR

**Comment by saitheexplorer** [comment]
```
{
    "extends": "eslint:recommended",

    "env": {
        "node": true,
        "es6": true
    },

    "rules": {
        "arrow-spacing": 2,
        "block-scoped-var": 2,
        "callback-return": 2,
        "handle-callback-err": 2,
        "no-path-concat": 2,
        "computed-property-spacing": [2, "never"],
        "eol-last": 2,
        "dot-notation": 2,
        "eqeqeq": 2,
        "indent": 2,
        "key-spacing": [2, {"beforeColon": false, "afterColon": true}],
        "no-mixed-spaces-and-tabs": 2,
        "no-else-return": 2,
        "no-multiple-empty-lines": [2, {"max": 1}],
        "no-var": 2,
        "no-eval": 2,
        "prefer-arrow-callback": 2,
        "prefer-const": 2,
        "prefer-template": 2,
        "quote-props": [2, "as-needed"],
        "quotes": [2, "single", "avoid-escape"]
    }
}
```

**Comment by saitheexplorer** [comment]
@nectarom/developers check this list out - anything you would add/change/remove?

**Comment by daniel-casper** [comment]
Will review - have you had a chance to look at my commit's specifications?

Also, please allow  trailing commas.

---

_Daniel J. Casper_
Integration Architect & Developer, NectarOM
_omnichannel personalization SaaS_

e: dcasper@nectarom.com  |  m: (214) 907-8770
www.nectarom.com | @nectarom http://www.twitter.com/nectarom

**Pull request merged**
